//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalar
    {
        public int HastalarID { get; set; }
        public string HastaTC { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public string Telefon { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeriID { get; set; }
        public string MedeniHali { get; set; }
        public string Email { get; set; }
        public Nullable<int> KanGrubuID { get; set; }
        public Nullable<decimal> HastaKilo { get; set; }
        public Nullable<decimal> HastaBoy { get; set; }
        public string Adres { get; set; }
        public string Acıklama { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual KanGruplari KanGruplari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
