//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Doktorlar
    {
        public int DoktorlarID { get; set; }
        public string DoktorTC { get; set; }
        public string DoktorAdi { get; set; }
        public string DoktorSoyadi { get; set; }
        public string DoktorCinsiyet { get; set; }
        public string DoktorTelefon { get; set; }
        public string Email { get; set; }
        public string MedeniHali { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string ilAdi { get; set; }
        public string KanGrubuAdi { get; set; }
        public string UnvanAdi { get; set; }
        public string Adres { get; set; }
        public string KullaniciAdi { get; set; }
        public string KlinikAdi { get; set; }
        public string Resim { get; set; }
    }
}
