//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoktorUnvanlari
    {
        public int DoktorUnvanlariID { get; set; }
        public string UnvanAdi { get; set; }
        public string BransAdi { get; set; }
        public string DiplomaNumarasi { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
