//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Gelirler
    {
        public int GelirlerID { get; set; }
        public string GelirAdi { get; set; }
        public decimal GelirMiktari { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
