//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KurumsalGiderler
    {
        public int KurumsalGiderlerID { get; set; }
        public string KurumAdi { get; set; }
        public string KurumAdres { get; set; }
        public string YetkiliTC { get; set; }
        public string YetkiliAdi { get; set; }
        public string YetkiliSoyadi { get; set; }
        public string KurumGiderKod { get; set; }
        public string GiderAdi { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
