//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Personeller
    {
        public int PersonellerID { get; set; }
        public string PersonelTC { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string ilAdi { get; set; }
        public string HesapNumarasi { get; set; }
        public string MedeniHali { get; set; }
        public byte[] Resim { get; set; }
        public string KanGrubuAdi { get; set; }
        public string Adres { get; set; }
        public string KullaniciAdi { get; set; }
    }
}
